# Generated by Django 5.0.4 on 2024-05-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspotapp', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='sweetspotapp.store'),
            preserve_default=False,
        ),
    ]
